// AUTO-GENERATED by scripts/generate-learn-registry.ts — do not edit manually

export const docContentMap: Record<string, string> = {
  "introduction": "# Introduction\n\nDocumentation for this page is being migrated into the website build.\n",
  "installation": "# Installation\n\nDocumentation for this page is being migrated into the website build.\n",
  "project-structure": "# Project Structure\n\nDocumentation for this page is being migrated into the website build.\n",
  "configuration": "# Configuration\n\nDocumentation for this page is being migrated into the website build.\n",
  "components": "# Components\n\nDocumentation for this page is being migrated into the website build.\n",
  "theming": "# Theming\n\nDocumentation for this page is being migrated into the website build.\n",
  "design-tokens": "# Design Tokens\n\nDocumentation for this page is being migrated into the website build.\n",
  "accessibility": "# Accessibility\n\nDocumentation for this page is being migrated into the website build.\n",
  "ui-library": "# Ui Library\n\nDocumentation for this page is being migrated into the website build.\n",
  "registry": "# Registry\n\nDocumentation for this page is being migrated into the website build.\n",
  "cli": "# Cli\n\nDocumentation for this page is being migrated into the website build.\n",
  "contracts": "# Contracts\n\nDocumentation for this page is being migrated into the website build.\n",
  "components-api": "# Components Api\n\nDocumentation for this page is being migrated into the website build.\n",
  "hooks-utilities": "# Hooks Utilities\n\nDocumentation for this page is being migrated into the website build.\n",
  "cli-commands": "# Cli Commands\n\nDocumentation for this page is being migrated into the website build.\n",
};
