import type { ComponentMeta } from "./types";

const GITHUB_BASE = "https://github.com/w3-kit/w3-kit/tree/main/ui/components";

export const componentRegistry: ComponentMeta[] = [
  // ── Wallet ──────────────────────────────────────────────
  {
    id: "connect-wallet",
    name: "Connect Wallet",
    description:
      "Wallet picker with multi-wallet support, connected state, chain switching, and disconnect. Pure UI — bring your own wallet logic.",
    category: "wallet",
    tags: ["metamask", "walletconnect", "coinbase", "phantom", "wagmi"],
    hasPreview: true,
    importPath: "w3-kit/connect-wallet",
    sourceUrl: `${GITHUB_BASE}/connect-wallet`,
    props: [
      {
        name: "wallets",
        type: "WalletOption[]",
        required: true,
        description: "List of wallets to display (id, name, icon, ecosystem)",
      },
      {
        name: "connectedAccount",
        type: "ConnectedAccount | null",
        required: false,
        description: "Connected account data. null = show wallet picker",
      },
      {
        name: "onConnect",
        type: "(walletId: string) => void",
        required: true,
        description: "Called when user selects a wallet to connect",
      },
      {
        name: "onDisconnect",
        type: "() => void",
        required: false,
        description: "Called when user clicks disconnect",
      },
      {
        name: "chains",
        type: "Chain[]",
        required: false,
        description: "Supported chains for the chain switcher",
      },
      {
        name: "activeChain",
        type: "Chain",
        required: false,
        description: "Currently active chain",
      },
      {
        name: "onChainSwitch",
        type: "(chainId: number) => void",
        required: false,
        description: "Called when user switches chain",
      },
      {
        name: "recentWalletId",
        type: "string",
        required: false,
        description: "ID of the most recently used wallet (shown highlighted)",
      },
      {
        name: "variant",
        type: '"default" | "compact"',
        required: false,
        default: '"default"',
        description: "default = full picker, compact = button that opens picker",
      },
      {
        name: "loading",
        type: "boolean",
        required: false,
        default: "false",
        description: "Show loading state on the selected wallet",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "network-switcher",
    name: "Network Switcher",
    description:
      "Clean list-based chain selector with testnet toggle, search, and per-chain loading state. Parent controls active chain.",
    category: "wallet",
    tags: ["chain", "network", "switch", "ethereum", "l2"],
    hasPreview: true,
    importPath: "w3-kit/network-switcher",
    sourceUrl: `${GITHUB_BASE}/network-switcher`,
    props: [
      {
        name: "networks",
        type: "Network[]",
        required: true,
        description: "All networks (use .testnet: true for testnets)",
      },
      {
        name: "activeChainId",
        type: "number",
        required: false,
        description: "Currently active chain ID (parent-controlled)",
      },
      {
        name: "onSwitch",
        type: "(chainId: number) => void | Promise<void>",
        required: true,
        description: "Called when user selects a network",
      },
      {
        name: "searchable",
        type: "boolean",
        required: false,
        default: "false",
        description: "Show search input (useful for large network lists)",
      },
      {
        name: "showTestnetToggle",
        type: "boolean",
        required: false,
        description: "Show testnet toggle (auto-detected from .testnet fields)",
      },
      {
        name: "switchingTo",
        type: "number",
        required: false,
        description: "Chain ID being switched to (shows loading spinner)",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "wallet-balance",
    name: "Wallet Balance",
    description:
      "Portfolio overview with total value, weighted 24h change, allocation bar with cross-hover, and token list sorted by value.",
    category: "wallet",
    tags: ["balance", "portfolio", "tokens", "allocation"],
    hasPreview: true,
    importPath: "w3-kit/wallet-balance",
    sourceUrl: `${GITHUB_BASE}/wallet-balance`,
    props: [
      {
        name: "tokens",
        type: "Token[]",
        required: true,
        description: "Tokens with balance, price, optional logo/color/priceChange24h",
      },
      {
        name: "onTokenClick",
        type: "(token: Token) => void",
        required: false,
        description: "Called when user clicks a token row",
      },
      {
        name: "onSend",
        type: "(token: Token) => void",
        required: false,
        description: "Called when user clicks send on a token",
      },
      {
        name: "onSwap",
        type: "(token: Token) => void",
        required: false,
        description: "Called when user clicks swap on a token",
      },
      {
        name: "onRefresh",
        type: "() => void | Promise<void>",
        required: false,
        description: "Refresh callback with loading spinner",
      },
      {
        name: "showAllocation",
        type: "boolean",
        required: false,
        default: "true",
        description: "Show allocation bar above token list",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "address-book",
    name: "Address Book",
    description: "Manage saved addresses with ENS name support, notes, and CRUD operations.",
    category: "wallet",
    tags: ["address", "ens", "contacts"],
    hasPreview: true,
    importPath: "w3-kit/address-book",
    sourceUrl: `${GITHUB_BASE}/address-book`,
    props: [
      {
        name: "entries",
        type: "AddressEntry[]",
        required: true,
        description: "List of saved address entries",
      },
      {
        name: "onAdd",
        type: "(entry: Omit<AddressEntry, 'id'>) => void",
        required: false,
        description: "Callback when adding a new entry",
      },
      {
        name: "onEdit",
        type: "(entry: AddressEntry) => void",
        required: false,
        description: "Callback when editing an entry",
      },
      {
        name: "onDelete",
        type: "(id: string) => void",
        required: false,
        description: "Callback when deleting an entry",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "multisig-wallet",
    name: "Multisig Wallet",
    description:
      "Multi-signature wallet with transaction list, approval progress bars, signer avatars, and tab filtering. Parent owns all state.",
    category: "wallet",
    tags: ["multisig", "gnosis", "safe", "approval"],
    hasPreview: true,
    importPath: "w3-kit/multisig-wallet",
    sourceUrl: `${GITHUB_BASE}/multisig-wallet`,
    props: [
      {
        name: "walletAddress",
        type: "string",
        required: true,
        description: "The multisig wallet address",
      },
      { name: "signers", type: "Signer[]", required: true, description: "List of wallet signers" },
      {
        name: "transactions",
        type: "Transaction[]",
        required: true,
        description: "Transaction list (parent-owned)",
      },
      {
        name: "requiredApprovals",
        type: "number",
        required: true,
        description: "Approval threshold",
      },
      {
        name: "onApprove",
        type: "(txId: string) => void",
        required: false,
        description: "Called when user approves a transaction",
      },
      {
        name: "onReject",
        type: "(txId: string) => void",
        required: false,
        description: "Called when user rejects a transaction",
      },
      {
        name: "onPropose",
        type: "() => void",
        required: false,
        description: "Called when user clicks propose (parent handles form)",
      },
      {
        name: "approvingId",
        type: "string",
        required: false,
        description: "Transaction ID being approved (shows loading)",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },

  // ── DeFi ────────────────────────────────────────────────
  {
    id: "token-swap",
    name: "Token Swap",
    description:
      "Clean swap widget with token selectors, flip button, exchange rate display, and inline dropdowns. Pure UI, parent provides rate.",
    category: "defi",
    tags: ["swap", "dex", "exchange", "uniswap"],
    hasPreview: true,
    importPath: "w3-kit/token-swap",
    sourceUrl: `${GITHUB_BASE}/token-swap`,
    props: [
      {
        name: "tokens",
        type: "SwapToken[]",
        required: true,
        description: "Available tokens for selection",
      },
      {
        name: "fromToken",
        type: "SwapToken",
        required: false,
        description: "Currently selected from token",
      },
      {
        name: "toToken",
        type: "SwapToken",
        required: false,
        description: "Currently selected to token",
      },
      {
        name: "onSwap",
        type: "(params: { from, to, amount }) => void | Promise<void>",
        required: true,
        description: "Called when user clicks swap",
      },
      {
        name: "onFromTokenChange",
        type: "(token: SwapToken) => void",
        required: false,
        description: "Called when user changes from token",
      },
      {
        name: "onToTokenChange",
        type: "(token: SwapToken) => void",
        required: false,
        description: "Called when user changes to token",
      },
      {
        name: "exchangeRate",
        type: "number",
        required: false,
        description: "How many toTokens per 1 fromToken",
      },
      {
        name: "slippage",
        type: "number",
        required: false,
        description: "Slippage tolerance percentage",
      },
      {
        name: "loading",
        type: "boolean",
        required: false,
        default: "false",
        description: "Loading state on swap button",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "staking-interface",
    name: "Staking Interface",
    description:
      "Props-driven staking pool list with expandable details, stake/unstake toggle, per-pool userStaked amount, and APR display. No injected CSS.",
    category: "defi",
    tags: ["staking", "yield", "apr", "pool"],
    hasPreview: true,
    importPath: "w3-kit/staking-interface",
    sourceUrl: `${GITHUB_BASE}/staking-interface`,
    props: [
      {
        name: "pools",
        type: "StakingPool[]",
        required: true,
        description:
          "Available staking pools (id, name, token, icon, apr, lockPeriod, totalStaked, userStaked, minStake)",
      },
      {
        name: "onStake",
        type: "(poolId: string, amount: string) => void",
        required: false,
        description: "Called when user stakes into a pool",
      },
      {
        name: "onUnstake",
        type: "(poolId: string, amount: string) => void",
        required: false,
        description: "Called when user unstakes from a pool",
      },
      {
        name: "stakingPoolId",
        type: "string",
        required: false,
        description: "Pool ID currently being staked to (shows loading spinner)",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "bridge",
    name: "Bridge Widget",
    description:
      "Cross-chain bridge UI with from/to network selectors, token picker, amount input, and swap button. Pure UI — parent controls all state via props.",
    category: "defi",
    tags: ["bridge", "cross-chain", "transfer", "l2"],
    hasPreview: true,
    importPath: "w3-kit/bridge",
    sourceUrl: `${GITHUB_BASE}/bridge`,
    props: [
      {
        name: "networks",
        type: "BridgeNetwork[]",
        required: true,
        description: "Available networks (id, name, icon?, color?)",
      },
      {
        name: "tokens",
        type: "BridgeToken[]",
        required: true,
        description: "Available tokens (symbol, name, icon?, balance?)",
      },
      {
        name: "fromNetwork",
        type: "BridgeNetwork",
        required: false,
        description: "Currently selected source network",
      },
      {
        name: "toNetwork",
        type: "BridgeNetwork",
        required: false,
        description: "Currently selected destination network",
      },
      {
        name: "selectedToken",
        type: "BridgeToken",
        required: false,
        description: "Currently selected token",
      },
      {
        name: "onBridge",
        type: "(params: { from, to, token, amount }) => void",
        required: false,
        description: "Called when user clicks the bridge button",
      },
      {
        name: "onFromNetworkChange",
        type: "(network: BridgeNetwork) => void",
        required: false,
        description: "Called when source network changes",
      },
      {
        name: "onToNetworkChange",
        type: "(network: BridgeNetwork) => void",
        required: false,
        description: "Called when destination network changes",
      },
      {
        name: "onTokenChange",
        type: "(token: BridgeToken) => void",
        required: false,
        description: "Called when token changes",
      },
      {
        name: "loading",
        type: "boolean",
        required: false,
        default: "false",
        description: "Show loading state on the bridge button",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "defi-position-manager",
    name: "DeFi Position Manager",
    description:
      "Clean position list with health factor bar, APY, and risk badges for open DeFi positions.",
    category: "defi",
    tags: ["position", "health", "apy", "risk"],
    hasPreview: true,
    importPath: "w3-kit/defi-position-manager",
    sourceUrl: `${GITHUB_BASE}/defi-position-manager`,
    props: [
      {
        name: "positions",
        type: "Position[]",
        required: true,
        description: "Array of DeFi positions to display",
      },
      {
        name: "onPositionClick",
        type: "(position: Position) => void",
        required: false,
        description: "Callback when a position row is clicked",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "flash-loan-executor",
    name: "Flash Loan Executor",
    description:
      "Props-driven flash loan UI with protocol selector, token dropdown, fee calculation, and execute button. Supports controlled and uncontrolled selection.",
    category: "defi",
    tags: ["flash-loan", "aave", "dydx", "arbitrage"],
    hasPreview: true,
    importPath: "w3-kit/flash-loan-executor",
    sourceUrl: `${GITHUB_BASE}/flash-loan-executor`,
    props: [
      {
        name: "protocols",
        type: "FlashLoanProtocol[]",
        required: true,
        description: "Available protocols (id, name, icon, fee)",
      },
      {
        name: "tokens",
        type: "FlashLoanToken[]",
        required: true,
        description: "Available tokens (symbol, name, icon, maxAmount)",
      },
      {
        name: "selectedProtocol",
        type: "FlashLoanProtocol",
        required: false,
        description: "Controlled selected protocol (uncontrolled if omitted)",
      },
      {
        name: "selectedToken",
        type: "FlashLoanToken",
        required: false,
        description: "Controlled selected token (uncontrolled if omitted)",
      },
      {
        name: "onExecute",
        type: "(params: { protocol, token, amount }) => void",
        required: false,
        description: "Called when user clicks execute with valid amount",
      },
      {
        name: "onProtocolChange",
        type: "(protocol: FlashLoanProtocol) => void",
        required: false,
        description: "Called when user switches protocol",
      },
      {
        name: "onTokenChange",
        type: "(token: FlashLoanToken) => void",
        required: false,
        description: "Called when user switches token",
      },
      {
        name: "loading",
        type: "boolean",
        required: false,
        default: "false",
        description: "Show loading spinner on execute button",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "limit-order-manager",
    name: "Limit Order Manager",
    description:
      "Clean order list with tab filtering (Active / Filled / All), buy/sell type badges, status indicators, and cancel with loading state. Parent owns all state.",
    category: "defi",
    tags: ["limit-order", "trading", "buy", "sell"],
    hasPreview: true,
    importPath: "w3-kit/limit-order-manager",
    sourceUrl: `${GITHUB_BASE}/limit-order-manager`,
    props: [
      {
        name: "orders",
        type: "LimitOrder[]",
        required: true,
        description: "Order list (id, type buy/sell, token, amount, price, status, timestamp)",
      },
      {
        name: "onCancel",
        type: "(orderId: string) => void",
        required: false,
        description: "Called when user cancels an active order",
      },
      {
        name: "onCreateOrder",
        type: "() => void",
        required: false,
        description: "Called when user clicks New Order (parent handles form)",
      },
      {
        name: "cancellingId",
        type: "string",
        required: false,
        description: "Order ID being cancelled (shows loading spinner)",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "liquidity-pool-stats",
    name: "Liquidity Pool Stats",
    description:
      "Clean pool stats card with TVL, volume, APR, fees, transactions, holders, and action buttons.",
    category: "defi",
    tags: ["liquidity", "pool", "tvl", "volume", "apr"],
    hasPreview: true,
    importPath: "w3-kit/liquidity-pool-stats",
    sourceUrl: `${GITHUB_BASE}/liquidity-pool-stats`,
    props: [
      {
        name: "pool",
        type: "PoolStats",
        required: true,
        description:
          "Pool statistics — tokenPair, fee, tvl, volume24h, apr, and optional change/count fields",
      },
      {
        name: "onAddLiquidity",
        type: "() => void",
        required: false,
        description: "Callback when Add Liquidity is clicked",
      },
      {
        name: "onRemoveLiquidity",
        type: "() => void",
        required: false,
        description: "Callback when Remove Liquidity is clicked",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },

  // ── NFT ─────────────────────────────────────────────────
  {
    id: "nft-card",
    name: "NFT Card",
    description:
      "NFT display card with image, collection badge, price, owner address, and attributes. Keyboard accessible with hover lift.",
    category: "nft",
    tags: ["nft", "collectible", "card"],
    hasPreview: true,
    importPath: "w3-kit/nft-card",
    sourceUrl: `${GITHUB_BASE}/nft-card`,
    props: [
      { name: "nft", type: "NFT", required: true, description: "NFT data object" },
      {
        name: "onClick",
        type: "(nft: NFT) => void",
        required: false,
        description: "Called when the card is clicked",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "nft-collection-grid",
    name: "NFT Collection Grid",
    description:
      "Responsive NFT grid with configurable columns, image placeholders, and hover effects. Parent controls data.",
    category: "nft",
    tags: ["nft", "collection", "grid", "gallery"],
    hasPreview: true,
    importPath: "w3-kit/nft-collection-grid",
    sourceUrl: `${GITHUB_BASE}/nft-collection-grid`,
    props: [
      {
        name: "items",
        type: "NFTItem[]",
        required: true,
        description: "Array of NFT items to display",
      },
      {
        name: "collectionName",
        type: "string",
        required: false,
        description: "Collection name for the header",
      },
      {
        name: "onItemClick",
        type: "(item: NFTItem) => void",
        required: false,
        description: "Called when an NFT item is clicked",
      },
      {
        name: "columns",
        type: "2 | 3 | 4",
        required: false,
        default: '"2"',
        description: "Number of grid columns",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "nft-marketplace-aggregator",
    name: "NFT Marketplace Aggregator",
    description:
      "Aggregated NFT listings from multiple marketplaces with best-price detection, marketplace badges, and buy button.",
    category: "nft",
    tags: ["marketplace", "opensea", "aggregator", "listing"],
    hasPreview: true,
    importPath: "w3-kit/nft-marketplace-aggregator",
    sourceUrl: `${GITHUB_BASE}/nft-marketplace-aggregator`,
    props: [
      {
        name: "listings",
        type: "NFTListing[]",
        required: true,
        description: "NFT listings to display",
      },
      {
        name: "onBuy",
        type: "(listing: NFTListing) => void",
        required: false,
        description: "Called when user clicks buy on a listing",
      },
      {
        name: "buyingId",
        type: "string",
        required: false,
        description: "Listing ID being purchased (loading)",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },

  // ── Data ────────────────────────────────────────────────
  {
    id: "asset-portfolio",
    name: "Asset Portfolio",
    description:
      "Portfolio overview with total value, weighted 24h change, allocation bar with cross-hover, and asset list sorted by value.",
    category: "data",
    tags: ["portfolio", "allocation", "balance", "chart"],
    hasPreview: true,
    importPath: "w3-kit/asset-portfolio",
    sourceUrl: `${GITHUB_BASE}/asset-portfolio`,
    props: [
      {
        name: "assets",
        type: "Asset[]",
        required: true,
        description: "Assets with symbol, name, balance, price, value, change24h, color",
      },
      {
        name: "totalValue",
        type: "number",
        required: true,
        description: "Total portfolio value in USD",
      },
      {
        name: "totalChange24h",
        type: "number",
        required: true,
        description: "24h portfolio change percentage",
      },
      {
        name: "onAssetClick",
        type: "(asset: Asset) => void",
        required: false,
        description: "Called when user clicks an asset",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "price-ticker",
    name: "Price Ticker",
    description:
      "Token price table with real-time prices, 24h change badges, and market cap. Rows are clickable.",
    category: "data",
    tags: ["price", "ticker", "market", "table"],
    hasPreview: true,
    importPath: "w3-kit/price-ticker",
    sourceUrl: `${GITHUB_BASE}/price-ticker`,
    props: [
      {
        name: "tokens",
        type: "Token[]",
        required: true,
        description: "Tokens with symbol, name, price, priceChange24h, marketCap, logoURI",
      },
      {
        name: "onTokenClick",
        type: "(token: Token) => void",
        required: false,
        description: "Called when user clicks a token row",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "token-card",
    name: "Token Card",
    description: "Single token detail card with price, balance, value, and 24h change indicator.",
    category: "data",
    tags: ["token", "card", "price"],
    hasPreview: true,
    importPath: "w3-kit/token-card",
    sourceUrl: `${GITHUB_BASE}/token-card`,
    props: [
      {
        name: "token",
        type: "Token",
        required: true,
        description: "Token with symbol, name, price, balance, priceChange24h, logoURI",
      },
      {
        name: "onClick",
        type: "(token: Token) => void",
        required: false,
        description: "Called when the card is clicked",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "token-list",
    name: "Token List",
    description: "Token table with balance and computed value columns. Sorted by value descending.",
    category: "data",
    tags: ["token", "list", "table"],
    hasPreview: true,
    importPath: "w3-kit/token-list",
    sourceUrl: `${GITHUB_BASE}/token-list`,
    props: [
      {
        name: "tokens",
        type: "Token[]",
        required: true,
        description: "Tokens with symbol, name, balance, price, logoURI",
      },
      {
        name: "onTokenSelect",
        type: "(token: Token) => void",
        required: false,
        description: "Called when user selects a token",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "transaction-history",
    name: "Transaction History",
    description:
      "Transaction list with type icons (send/receive/swap/contract), status badges, truncated addresses, and relative timestamps.",
    category: "data",
    tags: ["transaction", "history", "activity"],
    hasPreview: true,
    importPath: "w3-kit/transaction-history",
    sourceUrl: `${GITHUB_BASE}/transaction-history`,
    props: [
      {
        name: "transactions",
        type: "Transaction[]",
        required: true,
        description: "Transactions with hash, type, status, value, from, to, timestamp",
      },
      {
        name: "onTransactionClick",
        type: "(tx: Transaction) => void",
        required: false,
        description: "Called when user clicks a transaction",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },

  // ── Utility ─────────────────────────────────────────────
  {
    id: "smart-contract-scanner",
    name: "Smart Contract Scanner",
    description:
      "Security scanner displaying contract audit results with score, individual checks, and status badges. Pure UI — parent provides scan results.",
    category: "utility",
    tags: ["security", "audit", "scanner", "contract"],
    hasPreview: true,
    importPath: "w3-kit/smart-contract-scanner",
    sourceUrl: `${GITHUB_BASE}/smart-contract-scanner`,
    props: [
      {
        name: "address",
        type: "string",
        required: true,
        description: "Contract address being scanned",
      },
      { name: "score", type: "number", required: true, description: "Security score (0-100)" },
      {
        name: "checks",
        type: "SecurityCheck[]",
        required: true,
        description: "Individual check results (name, status: safe/warning/danger)",
      },
      {
        name: "onScan",
        type: "(address: string) => void",
        required: false,
        description: "Called when user enters a new address to scan",
      },
      {
        name: "loading",
        type: "boolean",
        required: false,
        default: "false",
        description: "Show loading state while scanning",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "contract-interaction",
    name: "Contract Interaction",
    description:
      "Action-based contract interaction with wizard flow: select contract → pick action → fill params → preview → execute. Human-readable labels, not raw ABI.",
    category: "utility",
    tags: ["contract", "abi", "read", "write"],
    hasPreview: true,
    importPath: "w3-kit/contract-interaction",
    sourceUrl: `${GITHUB_BASE}/contract-interaction`,
    props: [
      { name: "address", type: "string", required: false, description: "Contract address" },
      { name: "abi", type: "AbiFunction[]", required: false, description: "Parsed ABI functions" },
      {
        name: "actions",
        type: "Action[]",
        required: false,
        description: "Human-readable action definitions",
      },
      {
        name: "onCall",
        type: "(functionName: string, args: string[]) => Promise<string>",
        required: false,
        description: "Execute a contract call",
      },
      {
        name: "loading",
        type: "boolean",
        required: false,
        default: "false",
        description: "Show loading state",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "ens-resolver",
    name: "ENS Resolver",
    description:
      "ENS name resolution with search input, resolved result display, avatar, copy buttons, and bidirectional lookup.",
    category: "utility",
    tags: ["ens", "domain", "resolver"],
    hasPreview: true,
    importPath: "w3-kit/ens-resolver",
    sourceUrl: `${GITHUB_BASE}/ens-resolver`,
    props: [
      {
        name: "onResolve",
        type: "(result: ENSResult) => void",
        required: false,
        description: "Called with resolution result",
      },
      {
        name: "resolver",
        type: "(input: string) => Promise<ENSResult>",
        required: false,
        description: "Custom resolver function — parent provides the lookup logic",
      },
      {
        name: "defaultValue",
        type: "string",
        required: false,
        description: "Pre-filled search value",
      },
      {
        name: "loading",
        type: "boolean",
        required: false,
        default: "false",
        description: "Show loading state",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "gas-calculator",
    name: "Gas Calculator",
    description:
      "Gas estimation with 3 speed presets (Economy/Standard/Fast), gwei display, and estimated cost in ETH + USD.",
    category: "utility",
    tags: ["gas", "fee", "estimate", "gwei"],
    hasPreview: true,
    importPath: "w3-kit/gas-calculator",
    sourceUrl: `${GITHUB_BASE}/gas-calculator`,
    props: [
      {
        name: "speeds",
        type: "GasSpeed[]",
        required: true,
        description: "Speed options with name, gwei, time estimate, cost",
      },
      {
        name: "selectedSpeed",
        type: "string",
        required: false,
        description: "Currently selected speed ID",
      },
      {
        name: "onSelect",
        type: "(speedId: string) => void",
        required: false,
        description: "Called when user selects a speed",
      },
      {
        name: "ethPrice",
        type: "number",
        required: false,
        description: "ETH price in USD for cost calculation",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "subscription-payments",
    name: "Subscription Payments",
    description:
      "Crypto subscription plan cards with pricing, feature lists, popular badge, and subscribe button with loading state.",
    category: "utility",
    tags: ["subscription", "payments", "plans", "pricing"],
    hasPreview: true,
    importPath: "w3-kit/subscription-payments",
    sourceUrl: `${GITHUB_BASE}/subscription-payments`,
    props: [
      {
        name: "plans",
        type: "Plan[]",
        required: true,
        description: "Plans with id, name, price, token, interval, features[], popular?",
      },
      {
        name: "onSubscribe",
        type: "(planId: string) => void",
        required: false,
        description: "Called when user clicks subscribe",
      },
      {
        name: "subscribingId",
        type: "string",
        required: false,
        description: "Plan ID being subscribed to (loading)",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "token-airdrop",
    name: "Token Airdrop",
    description:
      "Airdrop list with status badges (active/claimed/expired), token amounts, dates, and claim button with loading state.",
    category: "utility",
    tags: ["airdrop", "claim", "merkle"],
    hasPreview: true,
    importPath: "w3-kit/token-airdrop",
    sourceUrl: `${GITHUB_BASE}/token-airdrop`,
    props: [
      {
        name: "airdrops",
        type: "Airdrop[]",
        required: true,
        description: "Airdrops with id, token, amount, status, startDate, endDate",
      },
      {
        name: "onClaim",
        type: "(airdropId: string) => void",
        required: false,
        description: "Called when user claims an airdrop",
      },
      {
        name: "claimingId",
        type: "string",
        required: false,
        description: "Airdrop ID being claimed (loading)",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "token-vesting",
    name: "Token Vesting",
    description:
      "Vesting schedule with progress bar, cliff/end dates, claimable amount, and claim button with loading state.",
    category: "utility",
    tags: ["vesting", "unlock", "schedule", "cliff"],
    hasPreview: true,
    importPath: "w3-kit/token-vesting",
    sourceUrl: `${GITHUB_BASE}/token-vesting`,
    props: [
      {
        name: "schedules",
        type: "VestingSchedule[]",
        required: true,
        description:
          "Schedules with id, token, totalAmount, vestedAmount, cliffDate, endDate, status",
      },
      {
        name: "onClaim",
        type: "(scheduleId: string) => void",
        required: false,
        description: "Called when user claims vested tokens",
      },
      {
        name: "claimingId",
        type: "string",
        required: false,
        description: "Schedule ID being claimed (loading)",
      },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
];

export const primitivesRegistry = [
  {
    id: "button",
    name: "Button",
    description: "Flexible button with multiple variants and sizes.",
  },
  { id: "badge", name: "Badge", description: "Small inline badge for status indicators." },
  {
    id: "card",
    name: "Card",
    description: "Composable card layout with header, content, and footer.",
  },
  { id: "dialog", name: "Dialog", description: "Accessible modal dialog built on Radix UI." },
  { id: "input", name: "Input", description: "Styled text input with focus states." },
  {
    id: "progress",
    name: "Progress",
    description: "Progress bar indicator with smooth animations.",
  },
  { id: "select", name: "Select", description: "Accessible dropdown select component." },
  { id: "stat", name: "Stat", description: "Statistic display with label and value." },
  {
    id: "status-dot",
    name: "Status Dot",
    description: "Colored dot for success, pending, or error.",
  },
  { id: "tabs", name: "Tabs", description: "Tab navigation with content panels." },
  { id: "textarea", name: "Textarea", description: "Styled textarea input element." },
  {
    id: "token-icon",
    name: "Token Icon",
    description: "Token logo with fallback to symbol abbreviation.",
  },
];
